install: 1

versions:
    ruby-193:
        default: '1'
        bundler: '1'
        version: 2.3.1
        gems:
            - deep_merge@1.0.1
            - activesupport@4.2.6
            - vine@0.2
